### ISSUE TITLE
리스트 관련 질문드립니다!

### ISSUE THREAD

**Issue by kyj960901** [hwonyo/naver_talk_sdk#38]
안녕하십니까?
만들어주신 sdk를 정말 유용하게 사용하고 있는 대학생입니다.
제가 쇼핑몰 재고를 받아와서 알려주는 챗봇을 만들고 있는데, 혹시 카드뷰에서 버튼 리스트의 버튼 갯수를 때에 따라 다르게 할 방법이 있을까요??

**Comment by HwangWonYo** [comment]
질문을 잘 이해했는지 모르겠네요;;
Template.Composite으로 카드뷰를 만들텐데
그때 파리미터 중 하나인 button_list의 값을 때에 따라서 다르게 적용하고 싶다는 말인가요?

이렇게 이해한게 맞다면
button_list는 list 타입을 인자로 받기 때문에 그냥 동적으로 list를 만들어서 적용하면 됩니다.
자세한 상황을 몰라서 밑에 예시를 대충 적어봤습니다.
```python
bt_list = []
if 내가 원하는 때:
    bt_list.append(Button(내가 원하는 버튼))

Template.Composite(title="~", description="~", button_list=bt_list)
```
